---
- name: Perform Google Search and Parse Results
  hosts: localhost
  vars:
    query: "{{ 'Who wrote the book Voodoo, Ltd. murder mystery' | urlencode }}"
  tasks:
    - name: Perform Google Search
      google_search:
        query: "{{ query }}"
        headers:
          User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      register: google_search_response
    - name: Set search results
      ansible.builtin.set_fact:
        html_content: "{{ google_search_response }}"
    - name: Let's see the results
      ansible.builtin.debug:
        var: html_content
